name: weberbrain_678_app
description: "WeberBrain 678"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  auto_route: ^7.9.0
  equatable: ^2.0.5
  logger: ^2.4.0
  dartz: ^0.10.1
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  flutter_blue_plus: ^1.33.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
