name: weberbrain_678_app
description: "WeberBrain 678"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  auto_route: ^7.9.0
  equatable: ^2.0.5
  logger: ^2.4.0
  dartz: ^0.10.1
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  flutter_blue_plus: ^1.33.4
  permission_handler: ^11.3.1
  flash: ^3.1.1
  rxdart: ^0.28.0
  collection: ^1.18.0
  # TODO Implement these dependencies
  # pinput: ^5.0.0
  # geolocator: ^13.0.1
  # sensors_plus: ^6.1.0
  # convex_bottom_bar: ^3.2.0
  # flutter_native_splash: ^2.4.1
  # flutter_slidable: ^3.1.1
  # intl: ^0.19.0
  # animated_text_kit: ^4.2.2
  # auto_size_text: ^3.0.0
  # flex_color_scheme: ^7.3.
  # flutter_local_notifications: ^17.2.3
  # fl_chart: ^0.69.0
  # smooth_page_indicator: ^1.2.0+3
  # flutter_launcher_icons: ^0.14.1
  # dropdown_button2: ^2.3.9
  # local_auth: ^2.3.0
  # hive: ^2.2.3
  # nfc_manager: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
